In [1]:
import numpy as np

In [3]:
l = list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
l2 = [ str(c) for c in l]
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [8]:
l3 = [True , '2','3',4,5]
l3

[True, '2', '3', 4, 5]

In [12]:
import array
A = array.array('i',l)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.array([1,4,5,3,4,32])

array([ 1,  4,  5,  3,  4, 32])

In [16]:
np.array([range(i,i+3) for i in [2,3,4]])

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [17]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.full((3,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [21]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [23]:
np.random.random((3,3))

array([[0.42382151, 0.85040551, 0.94505147],
       [0.53680324, 0.03154596, 0.36102049],
       [0.09214852, 0.00313478, 0.81918603]])

In [26]:
np.random.normal(0,10,(3,3))

array([[ 17.86453973,  -2.90934513,  16.63236832],
       [ -3.49053005,   3.28133884, -15.2534879 ],
       [-12.47835095,   4.38992447,   9.92736637]])

In [31]:
np.random.choice(5,5)

array([3, 1, 4, 3, 3])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.empty((3))

array([1., 1., 1.])

In [44]:
np.zeros(10,dtype = np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [2]:
np.random.seed(0)
x1 = np.random.randint(10,size=10)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))
print(x1,x2,x3)

[5 0 3 3 7 9 3 5 2 4] [[7 6 8 8]
 [1 6 7 7]
 [8 1 5 9]] [[[8 9 4 3 0]
  [3 5 0 2 3]
  [8 1 3 3 3]
  [7 0 1 9 9]]

 [[0 4 7 3 2]
  [7 2 0 0 4]
  [5 5 6 8 4]
  [1 4 9 8 1]]

 [[1 7 9 9 3]
  [6 7 2 0 3]
  [5 9 4 4 6]
  [4 4 3 4 4]]]


In [48]:
x3.ndim

3

In [50]:
x3.shape

(3, 4, 5)

In [51]:
x3.dtype

dtype('int32')

In [52]:
x3.itemsize

4

In [53]:
x3.nbytes

240

In [4]:
grid = np.arange(1,10).reshape((3,3))

In [5]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
x1[np.newaxis,:]

array([[5, 0, 3, 3, 7, 9, 3, 5, 2, 4]])

In [63]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

In [65]:
np.concatenate([x,y])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [75]:
np.vstack([x,y])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [76]:
np.hstack([x,y])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
np.split(x1,[3,5])

[array([5, 0, 3]), array([3, 7]), array([9, 3, 5, 2, 4])]

In [90]:
np.vsplit(grid,[2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

In [93]:
np.hsplit(grid,[1])

[array([[1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

In [6]:
print(grid*3,'\n\n',grid+4,'\n\n',grid-3,'\n\n',grid/3)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]] 

 [[ 5  6  7]
 [ 8  9 10]
 [11 12 13]] 

 [[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]] 

 [[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


In [13]:
c  = np.arange(0,10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
[c[0],c[2],c[5],grid[0][1],grid[1][0]]

[0, 2, 5, 2, 4]

In [14]:
from scipy import special

In [19]:
print(special.beta(c[1],2),special.gamma(c[1]))

0.5 1.0


In [22]:
print(np.log(c[1]),'\n\n',np.exp(c[1]))

0.0 

 2.718281828459045


In [35]:
print(np.log10(c[2]),'\n\n',np.expm1(c[2]))

0.3010299956639812 

 6.38905609893065


In [39]:
print(np.power(3,c[2]))

9


In [42]:
d = np.random.randint(1,100,10000)
d

array([50, 13, 18, ...,  3, 31, 52])

In [43]:
%timeit d

46.7 ns ± 0.453 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [45]:
lst = [2.3,4.3,5.3,4.4,5.3]
lst

[2.3, 4.3, 5.3, 4.4, 5.3]

In [50]:
lst1 = list()
for i in lst:
    c = abs(i)
    lst1.append(c)
lst1

[2.3, 4.3, 5.3, 4.4, 5.3]

5.3